# Generated by Django 4.1.7 on 2023-02-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('app_permission', models.CharField(default='1', max_length=10)),
                ('app_status', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dep_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100, unique=True)),
                ('dep_status', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_code', models.CharField(max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('national', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('address', models.TextField(default='', null=True)),
                ('subdistrict', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('img_profile', models.ImageField(default='', null=True, upload_to='static/employee/')),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.appointment')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.department')),
            ],
        ),
    ]
