# Generated by Django 4.1.7 on 2023-02-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_Cus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('app_permission', models.CharField(default='1', max_length=10)),
                ('app_status', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dep_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dep_name_th', models.CharField(max_length=100, unique=True)),
                ('dep_name_en', models.CharField(max_length=100, unique=True)),
                ('dep_status', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_code', models.CharField(max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('national', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('address', models.TextField(default='', null=True)),
                ('subdistrict', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('img_profile', models.ImageField(blank=True, default='', null=True, upload_to='static/images/employee/')),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.appointment')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.department')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('tel_order', models.CharField(max_length=10)),
                ('order_img', models.ImageField(default='', upload_to='static/images/orders/')),
                ('order_status', models.IntegerField(default=0)),
                ('create_date_time', models.CharField(max_length=50)),
                ('submit_date_time', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_Cus.customer')),
                ('submit_emp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='order_receive',
            fields=[
                ('order_rec_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_rec_date', models.CharField(max_length=50)),
                ('order_rec_status', models.CharField(default='1', max_length=1)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.order')),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('tool_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100, unique=True)),
                ('tool_price', models.FloatField(default=0.0)),
                ('tool_des', models.TextField(blank=True, default='', null=True)),
                ('tool_img', models.ImageField(blank=True, default='', null=True, upload_to='static/images/tool/')),
            ],
        ),
        migrations.CreateModel(
            name='tooltype',
            fields=[
                ('tooly_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tooly_name', models.CharField(max_length=100, unique=True)),
                ('tooly_status', models.BooleanField(default='True')),
                ('tooly_des', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tool_use',
            fields=[
                ('tu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tu_total_price', models.FloatField(default=0.0)),
                ('tu_amount', models.IntegerField(default=1)),
                ('tu_get_date', models.CharField(max_length=50)),
                ('order_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.order_receive')),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.tooltype'),
        ),
        migrations.CreateModel(
            name='repair_detail',
            fields=[
                ('re_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('re_detail', models.TextField()),
                ('re_date_start', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('re_date_end', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.employee')),
                ('order_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.order_receive')),
            ],
        ),
        migrations.CreateModel(
            name='order_queue',
            fields=[
                ('order_que_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_que_number', models.IntegerField(default=1)),
                ('order_que_date', models.CharField(max_length=50)),
                ('order_que_status', models.CharField(default='1', max_length=1)),
                ('order_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.order_receive')),
            ],
        ),
    ]
