# Generated by Django 4.1.7 on 2023-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0002_alter_employee_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img_profile',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/employee/'),
        ),
    ]
