# Generated by Django 4.1.7 on 2023-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0003_order_receive_price_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool_use',
            old_name='tool_id',
            new_name='tool',
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_img',
            field=models.ImageField(default='', upload_to='static/images/tool/'),
        ),
    ]
