# Generated by Django 4.1.7 on 2023-02-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0004_rename_tool_id_tool_use_tool_alter_tool_tool_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('pay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=1)),
                ('pay_img', models.ImageField(blank=True, default='', null=True, upload_to='static/images/pay/')),
                ('pay_status', models.CharField(max_length=1)),
                ('pay_date_send', models.CharField(max_length=50)),
                ('pay_date_check', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.order_receive')),
            ],
        ),
    ]
