# Generated by Django 4.1.7 on 2023-02-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0004_tooltype_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_price',
            field=models.FloatField(default=0.0),
        ),
    ]
