# Generated by Django 4.1.7 on 2023-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0005_alter_tool_tool_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/tool/'),
        ),
    ]
