# Generated by Django 4.1.7 on 2023-02-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0005_alter_cus_address_cus'),
        ('Project_UserEmp', '0007_order_receive_price_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.appointment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.department'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Project_Cus.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit_emp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.employee'),
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='order_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.order_receive', unique=True),
        ),
        migrations.AlterField(
            model_name='order_queue',
            name='order_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.order_receive'),
        ),
        migrations.AlterField(
            model_name='order_receive',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.employee'),
        ),
        migrations.AlterField(
            model_name='order_receive',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.order'),
        ),
        migrations.AlterField(
            model_name='repair_detail',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.employee'),
        ),
        migrations.AlterField(
            model_name='repair_detail',
            name='order_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.order_receive', unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.tooltype'),
        ),
        migrations.AlterField(
            model_name='tool_use',
            name='order_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.order_receive'),
        ),
        migrations.AlterField(
            model_name='tool_use',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_UserEmp.tool'),
        ),
    ]
