# Generated by Django 4.1.7 on 2023-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
