# Generated by Django 4.1.7 on 2023-02-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subdistrict',
        ),
        migrations.CreateModel(
            name='cus_address',
            fields=[
                ('cus_add', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('subdistrict', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('note', models.TextField()),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Cus.customer')),
            ],
        ),
    ]
