# Generated by Django 4.1.7 on 2023-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0002_remove_customer_province_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cus_address',
            old_name='cus_id',
            new_name='cus',
        ),
        migrations.AlterField(
            model_name='cus_address',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
