# Generated by Django 4.1.7 on 2023-02-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='cus_id',
        ),
    ]
