# Generated by Django 4.1.7 on 2023-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0003_rename_cus_id_cus_address_cus_alter_cus_address_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_address',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
