# Generated by Django 4.1.7 on 2023-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0006_alter_tool_tool_img'),
        ('Project_Cus', '0003_rename_id_customer_cus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('tel_order', models.CharField(max_length=10)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('submit_date_time', models.DateField(blank=True, default='', null=True)),
                ('cus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_Cus.customer')),
                ('submit_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.employee')),
            ],
        ),
    ]
