# Generated by Django 4.1.7 on 2023-02-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UserEmp', '0006_alter_tool_tool_img'),
        ('Project_Cus', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_UserEmp.employee'),
        ),
    ]
