# Generated by Django 4.1.7 on 2023-02-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0004_alter_cus_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_address',
            name='cus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project_Cus.customer'),
        ),
    ]
