# Generated by Django 4.1.7 on 2023-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Cus', '0005_alter_order_submit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_img',
            field=models.ImageField(default='', upload_to='static/images/orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
